### ISSUE TITLE
How do you find to what percentage two documents are similar using sense2vec?

### ISSUE THREAD

**Issue by Praveena0989** [explosion/sense2vec#29]
Consider I have two documents in English and how can I find by what percentage they are discussing the same thing in both documents using `sense2vec`

**Comment by ericzhao28** [comment]
For a quick solution, find the average of the word embeddings from each of the documents, and compute cosine distance. If you want to be more precise, this problem is an extremely active area of research. The Explosion team themselves wrote a blog about using CNNs (attention modeling) to compute the semantic difference between sentences (which can be extended into documents albeit with a computational cost): [https://explosion.ai/blog/quora-deep-text-pair-classification](url).
