### ISSUE TITLE
Assertion error loading vector map

### ISSUE THREAD

**Issue by sunwei317** [explosion/sense2vec#39]
Model was trained with Gensim 1.0, and then converted into Sense2vec format with gensim2sense.py after adding wv for it to work with the new version of Gensim. After generating the three files freqs.json, vectors.bin and strings.json, loading the model with Vector_map has the following problem:

  File "sense2vec/vectors.pyx", line 208, in sense2vec.vectors.VectorMap.load (sense2vec/vectors.cpp:6016)
  File "sense2vec/vectors.pyx", line 319, in sense2vec.vectors.VectorStore.load (sense2vec/vectors.cpp:8554)
  File "sense2vec/vectors.pyx", line 238, in sense2vec.vectors.VectorStore.add (sense2vec/vectors.cpp:7182)
AssertionError

It works before, except training the model with very older Gensim, which I cannot remember the version. Help is appreciated!

**Comment by jediwarpraptor** [comment]
I just got the same error using vectors trained with prodigy `terms.train-vector`.  The "vectors" file created by that process didn't have an extension.  I had to copy `vectors` to `vectors.bin` to get as far as I did.  Otherwise, I get the error that it cannot find `vectors.bin`.

Any thoughts?  I don't see a resolution on this issue, just a close.

**Comment by sayak1711** [comment]
Even I got the same error. Searching for the solution

**Comment by HiranD** [comment]
I have been able solve the same error in _sense2vec==1.0.0a0_ and _gensim==3.7_ by changing the dimension of the word vector to 128 (`size=128`) when training a new model. Because `sense2vec.load()` method is hard-coded to `VectorMap(128)` in `__init__.py`
