### ISSUE TITLE
Default pos while querying

### ISSUE THREAD

**Issue by sanjanaramprasad** [explosion/sense2vec#41]
I've seen in the demo, queries can be made without specifying POS tag and it defaults to an "auto" sense. Is there a way to replicate the same while querying with this model too? Or a way to query phrases like the "fair_game" example in the demo?

**Comment by dcarroll314** [comment]
Very interested in this as well. I think I could throw together a solution but something tells me the folks at Explosion have a much more elegant method. Given a string, if it is a match for the spelling of a set of word meanings then choose the most frequent POS tag for that spelling from the corpus. For example I'd assume "brown" would go to ADJ rather than NOUN. I'm pretty sure this is what the folks at Explosion are doing. 

A hack work around to this would be to use a dictionary library, check if the word is in the dictionary, grab it's part of speech and then pass it on. The problem is that the exact beauty of sense2vec is it's ability to interpret words that aren't in the dictionary. 

If we fail to find the word in the dictionary we could then try to take a pretty stupid approach and just try/catch with each of the POS until something works.

**Comment by elyase** [comment]
You can take a look at the logic followed in the demo [here](https://github.com/explosion/spacy-services/blob/master/sense2vec/sense2vec_service/similarity.py):
