### ISSUE TITLE
Similarity using Sense2Vec along with Spacy

### ISSUE THREAD

**Issue by armsp** [explosion/sense2vec#53]
I am not able to leverage the similarity examples from the blog or issue #24 to my case. I just wanted to get the "sense" of "**bear**" i.e Homonyms in an example like _"The bear growled. She could not bear the pain."_ 

```
import spacy
nlp = spacy.load("en_core_web_md")
from sense2vec import Sense2VecComponent
text = "The bear growled. She could not bear the pain."
s2v = Sense2VecComponent('./reddit_vectors-1.1.0')
nlp.add_pipe(s2v)
doc = nlp(text)
```
After this i can't get any official reference for the similarity API that took two vectors. I have tried with the following but i get errors-
```
s2v._.similarity(doc[1]._.s2v_vec,doc[6]._.s2v_vec)
nlp._.similarity(doc[1]._.s2v_vec,doc[6]._.s2v_vec)
```

**Comment by armsp** [comment]
@ines i was following this article https://explosion.ai/blog/sense2vec-with-spacy
I wanted to find the similarity between **bear|NOUN** and **bear|VERB** just for testing purposes. I wanted to see if sense2vec differentiates them.
Spacy gives the exact same vector to both since it actually works on the word's Lemma. 
What i am trying to figure out is if i can find words/sentences that are ambiguous like **_He went to the bank._** where bank can have multiple meanings. I am not sure how sense2vec would help me but i wanted to know.

**Comment by armsp** [comment]
With reference to your last comment _**"If you already know the words and their senses, you can also just use the sense2vec library directly and not via spaCy. Just look up the terms and you'll get a vector."**_

Are there any ways to find the sense of the word if its not given already? Also is it possible to find those words in the first place?

**Comment by ines** [comment]
> Are there any ways to find the sense of the word if its not given already? Also is it possible to find those words in the first place?

Well, in that case, you can use spaCy's part-of-speech tags, which should be fairly accurate. Using the sense2vec spaCy extension also makes sense then, because it lets you get the sense2vec vector straight from the token.

> Also is it possible to find those words in the first place?

Do you mean, if you have a bunch of text and want to find homonyms in it? You can always load in [existing lists](https://en.wikipedia.org/wiki/List_of_true_homonyms), use the [`Matcher`](http://spacy.io/usage/linguistic-features#rule-based-matching) to find them and then compare the POS tags etc. You could also iterate over the tokens in your text, find tokens that have the same `token.text` and then compare them (and store their `Doc` or sentence `Span` if you've found the same token text with different POS tags).

(Just keep in mind that models are statistical and the tagger can always make mistakes, too – especially for words that are ambiguous like this.)

**Comment by armsp** [comment]
Thanks @ines That is a good starting point. It can handle cases when we have a bunch of text.
However what about the case when we have a single sentence like **_"I went to the bank."_** Is there no other way than comparing the Wikipedia list with the tokens to tell that **bank** is ambiguous?

**Comment by ines** [comment]
> However what about the case when we have a single sentence like "I went to the bank." Is there no other way than comparing the Wikipedia list with the tokens to tell that bank is ambiguous?

In our [sense2vec demo](https://explosion.ai/demos/sense2vec), we've added an "auto" option that tries to guess the best-matching sense. We do this by simply iterating over the available options and getting the one with the highest frequency. You can [find the relevant bit of code here](https://github.com/explosion/spacy-services/blob/master/sense2vec/app.py#L58).

You could do something similar for your nouns and verbs, and check whether there are other entries for different part-of-speech tags (for example, check for `VERB` if your target word in a `NOUN`). You can then check the frequency and if it's reasonably high, it's a possible homonym. (You definitely want to use a high enough frequency threshold, though – otherwise, it might also turn up entries that got assigned incorrect POS tags. For example, "cat" might have been mistakenly tagged as a verb once or twice.)

**Comment by ines** [comment]
Closing this, since #77 will address a bunch of interoperability stuff with spaCy. Also, various things have changed under the hood in the meantime.
