### ISSUE TITLE
most_similar method

### ISSUE THREAD

**Issue by jehrodrigues** [explosion/sense2vec#60]
I would like to do operations of type trained_model.most_similar (positive = ['woman', 'king'], negative = ['man']) = [('queen', 0.50882536), ...], however, of sense2vec does not expect positive and negative parameters. Did someone have to do this implementation? Is this planned to be developed at sense2vec?

**Comment by ines** [comment]
Closing this, since various things have changed under the hood in the meantime and we're about to release #77, which uses spaCy's `Vectors.most_similar` under the hood.

The method doesn't support any of the positive/negative logic you're looking for. However, you can get the vectors out and then do your own vector math. See here for the implementation of spaCy's `most_similar`: https://github.com/explosion/spaCy/blob/c2f5f9f5727fd854a6147e71ed6625b7c57c4150/spacy/vectors.pyx#L306-L357
