### ISSUE TITLE
Retraining on newer reddit corpus?

### ISSUE THREAD

**Issue by petulla** [explosion/sense2vec#85]
Hello! I love this library. Thank you for it.

I'm wondering two things. 

1. Is there a newer version of this that someone should be using/alternative library I don't know about? I haven't found a great solution for phrase vectors.
2. If someone were to retrain the model on a newer Reddit corpus, do you have instructions for your first training that could serve as a template?

Thank you!

**Comment by ines** [comment]
Hi! The latest release of `sense2vec` was published 8 days ago – it's still an alpha, but it was rewritten from scratch and works with the latest version of spaCy. See here for installation instructions: https://github.com/explosion/sense2vec#-installation--setup

> If someone were to retrain the model on a newer Reddit corpus, do you have instructions for your first training that could serve as a template?

See here for the training scripts (with options for GloVe and Word2Vec via FastText, depending on what you prefer): https://github.com/explosion/sense2vec#-training-your-own-sense2vec-vectors

The parsing and preprocessing scripts are designed to work on individual files, so you can paralellize it more easily. We actually just finished parsing the entire Reddit corpus (150 billion words) and training a sense2vec model on that.

@honnibal shared some more details on the process here: https://twitter.com/honnibal/status/1193039671313477633

**Comment by petulla** [comment]
Thanks. Sorry one point of confusion. The model in the latest release, is it then not 2015 Reddit but the model Matthew parsed? I mean the one attached here:

https://github.com/explosion/sense2vec/releases/tag/v1.0.0a2

If so, the first reference to Reddit in the Readme says 2015 Reddit corpus. I can make a PR to clarify the readme if it helps.

**Comment by ines** [comment]
Ohh, sorry, I think I misread your question. I thought you were referring to the library version, not the model (there has been some confusion since the alpha isn't the default version you get served on pip).

So yes, you're right – this artifact is just a converted version of the old 2015 Reddit vectors. We haven't tested or uploaded the new model yet, but we will soon! (We also need to decide how we want to distribute it – it probably makes sense to also have a smaller version with a smaller sample of recent Reddit.)

**Comment by petulla** [comment]
Cool. Any idea when it will be distributed? I'm looking to learn how to do the model training (I've posted similar issues on training an Entity Linker on SpaCy). So, if it's a ways off, may take a shot at training at least a sm version.

**Comment by pathapatisivayya** [comment]
hi 

please any one suggested me 

i  am getting  this error .
here i am attaching screenshot
![error23](https://user-images.githubusercontent.com/36192404/69343321-6f954200-0c93-11ea-8dc5-0d8a5ad31fa3.png)

**Comment by ines** [comment]
Just released v1.0. The new vector models (2015 and 2019) are attached to the release. See here for details: https://github.com/explosion/sense2vec/tree/master#pretrained-vectors

@pathapatisivayya It looks like you're passing the file path to the component instead of calling `from_disk`. See the docs for how to load in vectors and use the API: https://github.com/explosion/sense2vec/tree/master#usage-with-spacy-v22
